[package]
name = "fog_of_war"
version = "0.1.0"
authors = ["Hampus Hallkvist <hallkvi@kth.org>", "Isak Einberg <ieinberg@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"